config/routes.rb
# frozen_string_literal: true

Transeasy::Engine.routes.draw do
  root 'translations#index'

  get '/setup', to: 'translations#setup'

  resource :translations do
    member do
      post :save_setup
      get :clear_database if Rails.env.test?
      get :import_translation_file
      get :edit_translation_file
      post :create_translation_file
      patch :update_translation_file
      patch :delete_translation_file
      get :edit_translations
      post :add_translation
    end
    collection do
      get :index
    end
  end
end

app/models/transeasy/application_record.rb
# frozen_string_literal: true

module Transeasy
  # Empty application record for now
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/transeasy/translation_file.rb
# frozen_string_literal: true

module Transeasy
  # The key for each translation
  class TranslationFile < ApplicationRecord
    def self.rename_files(old_name, new_name)
      settings = TranslationSetting.first
      JSON.parse(settings.target_languages).each do |l|
        language_short = Transeasy.config.all_languages.find { |x| x[:title] == l }[:lang]

        raise 'Target language not found while renaming files!' unless language_short

        if File.exist?(Transeasy.full_file_name(old_name, language_short))
          File.rename(Transeasy.full_file_name(old_name, language_short),
                      Transeasy.full_file_name(new_name, language_short))
        end
      end
    end

    def create_files
      require 'yaml'
      settings = TranslationSetting.first
      JSON.parse(settings.target_languages).each do |l|
        language_short = Transeasy.config.all_languages.find { |x| x[:title] == l }[:lang]

        raise 'Target language not found while creating files!' unless language_short

        if File.exist?((full_name = full_file_name(language_short)))
          raise "File #{file_name} cannot be created because it already exists"
        end

        empty_file = { language_short.to_sym => { hello: 'world' } }.to_yaml
        File.write(full_name, empty_file)
      end
    end

    def delete_files
      settings = TranslationSetting.first
      JSON.parse(settings.target_languages).each do |l|
        language_short = Transeasy.config.all_languages.find { |x| x[:title] == l }[:lang]
        if File.exist?((full_name = full_file_name(language_short)))
          File.delete(full_name)
        end
      end
    end

    def all_translations
      []
    end

    def full_file_name(language)
      TranslationFile.full_file_name(file_name, language)
    end

    def self.full_file_name(file_name, language)
      "#{Transeasy.config.locales_path}/#{file_name}_#{language}.yml"
    end
  end
end

app/models/transeasy/translation_key.rb
# frozen_string_literal: true

module Transeasy
  # The key for each translation
  class TranslationKey < ApplicationRecord
    has_many :translation_values, class_name: 'Transeasy::TranslationValue', dependent: :destroy

    validates :key, presence: true, uniqueness: { case_sensitive: false }
  end
end

app/models/transeasy/translation_setting.rb
# frozen_string_literal: true

module Transeasy
  # The application settings
  class TranslationSetting < ApplicationRecord
    include ApplicationHelper

    validates :root_language, presence: true
    validates :target_languages, presence: true

    validate :check_translation_engine
    validate :target_languages_are_valid
    validate :root_language_not_target_language

    def check_translation_engine
      Transeasy.config.all_translation_engines.map { |e| e[:name] }.include?(translation_engine)
    end

    def target_languages_are_valid
      unless target_languages.instance_of?(String)
        errors.add(:target_languages, "Invalid class #{target_languages.class} for target languages")
        return false
      end

      all_titles = Transeasy.config.all_languages.map { |l| l[:title] }
      JSON.parse(target_languages)&.each do |l|
        next if all_titles.include?(l)

        errors.add(:target_languages, "Invalid target language #{l}")
      end
    end

    def root_language_not_target_language
      return if target_languages.blank?
      return unless JSON.parse(target_languages)&.include?(root_language)

      errors.add(:root_language, 'Root language cannot also be a target language')
    end
  end
end

app/models/transeasy/translation_value.rb
# frozen_string_literal: true

module Transeasy
  # The translations
  class TranslationValue < ApplicationRecord
    belongs_to :translation_key, class_name: 'Transeasy::TranslationKey'
  end
end

app/controllers/transeasy/application_controller.rb
# frozen_string_literal: true

module Transeasy
  # Basic application controller
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
  end
end

app/controllers/transeasy/translations_controller.rb
# frozen_string_literal: true

module Transeasy
  # Controller for translations
  class TranslationsController < ApplicationController
    before_action :check_setup, except: %i[save_setup setup]

    def index
      @translation_files = TranslationFile.all

      return if ActiveRecord::Base.connection.data_source_exists?('transeasy_translation_settings')

      flash.alert = 'Has migration not yet been performed? Missing database'
    end

    def setup
      @settings = TranslationSetting.first_or_create
    end

    def save_setup
      @settings = TranslationSetting.first_or_create
      if params[:target_languages].blank?
        flash[:alert] = 'Changes not saved. At least one target language must be selected'
      elsif @settings.update(setup_params)
        flash[:notice] = @settings.previous_changes.any? ? 'Changes saved' : 'No changes made'
      else
        flash[:alert] = "Changes not saved. #{@settings.errors.full_messages.join(',')}"
      end
      render :setup
    end

    def check_setup
      @settings = TranslationSetting.first_or_create
      redirect_to :setup unless @settings.persisted?
    end

    def import_translation_file; end

    def edit_translation_file
      return if (@translation_file = TranslationFile.find_by(id: params['id']))

      @translation_file = TranslationFile.new
    end

    def create_translation_file
      file_name = params['translation_file']['file_name']

      if TranslationFile.find_by(file_name:)
        flash[:alert] = "File #{file_name} already exists"
      elsif (@translation_file = TranslationFile.create(create_translation_file_params))
        @translation_file.create_files
        flash[:notice] = "Translation File #{file_name} created"
      else
        flash[:alert] = "File #{file_name} could not be created.
            Errors : #{@translation_file.errors.full_messages.join(', ')}"
      end
      redirect_to :translations
    end

    def update_translation_file
      @translation_file = TranslationFile.find(params['translation_file']['id'])

      if @translation_file.update(create_translation_file_params)
        flash[:notice] = if @translation_file.previous_changes.any?
                           change = @translation_file.previous_changes['file_name']
                           TranslationFile.rename_files(change[0], change[1])
                           "Translation File #{params['file_name']} updated"
                         else
                           'No changes made'
                         end
      else
        flash[:alert] = "File #{params['file_name']} could not be updated.
            Errors : #{@translation_file.errors.full_messages.join(', ')}"
      end

      redirect_to :translations
    end

    def delete_translation_file
      translation_file = TranslationFile.find(params[:id])
      name = translation_file.file_name
      translation_file.delete_files
      if translation_file.destroy
        flash[:notice] = "File #{name} destroyed"
      else
        flash[:alert] =
          "File #{name} could not be destroyed. Errors : #{translation_file.errors.full_messages.join(', ')}"
      end

      redirect_to :translations
    end

    def edit_translations
      translation_file = TranslationFile.find(params[:id])

      render :edit_translations, locals: { translations: translation_file.all_translations }
    end

    def clear_database
      return unless Rails.env.test?

      TranslationSetting.destroy_all
      flash[:notice] = 'Databases cleared'

      redirect_to :setup
    end

    private

    def setup_params
      params.permit(:root_language, :translation_engine, :translation_engine_parameters, target_languages: [])
    end

    def create_translation_file_params
      params.require(:translation_file).permit(:file_name, :id)
    end
  end
end

app/helpers/transeasy/application_helper.rb
# frozen_string_literal: true

module Transeasy
  # Empty application helper for now...
  module ApplicationHelper
  end
end

app/views/layouts/transeasy/application.html.slim
- @title = "TransEasy"

doctype html
html
  head
    title = @title
    = csrf_meta_tags
    meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0"

    script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" referrerpolicy="no-referrer"

    link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous"
    script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"

    script src="https://cdn.jsdelivr.net/npm/@rails/ujs@7.0.4-3/lib/assets/compiled/rails-ujs.min.js"

    link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slim-select/2.4.5/slimselect.min.css" integrity="sha512-GvqWM4KWH8mbgWIyvwdH8HgjUbyZTXrCq0sjGij9fDNiXz3vJoy3jCcAaWNekH2rJe4hXVWCJKN+bEW8V7AAEQ==" crossorigin="anonymous" referrerpolicy="no-referrer"
    script src="https://cdnjs.cloudflare.com/ajax/libs/slim-select/2.4.5/slimselect.global.min.js" integrity="sha512-r2ujllVbPV4gVNZyqAB6LS3cnpEenEl18yFYoowmutUX5zVXQi5mp13lMWv3FQpsn96eFJTcd5VqBkZuatGtWQ==" crossorigin="anonymous" referrerpolicy="no-referrer"

    script src="https://cdnjs.cloudflare.com/ajax/libs/autosize.js/3.0.20/autosize.min.js" integrity="sha512-EAEoidLzhKrfVg7qX8xZFEAebhmBMsXrIcI0h7VPx2CyAyFHuDvOAUs9CEATB2Ou2/kuWEDtluEVrQcjXBy9yw==" crossorigin="anonymous" referrerpolicy="no-referrer"

    link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/3.2.1/css/font-awesome.min.css" integrity="sha512-IJ+BZHGlT4K43sqBGUzJ90pcxfkREDVZPZxeexRigVL8rzdw/gyJIflDahMdNzBww4k0WxpyaWpC2PLQUWmMUQ==" crossorigin="anonymous" referrerpolicy="no-referrer"
    link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha512-SfTiTlX6kk+qitfevl/7LibUOeJWlt9rbyDn92a1DqWOw9vWG2MFoays0sgObmWazO5BQPiFucnnEAjpAB+/Sw==" crossorigin="anonymous" referrerpolicy="no-referrer"
    = stylesheet_link_tag 'transeasy', media: 'all', 'data-turbolinks-track': 'reload'

  body
    .container.mt-5
      = render 'transeasy/shared/flash'
      = render 'transeasy/shared/nav'

      = yield

javascript:
    document.addEventListener("DOMContentLoaded", function() {
        $("form").attr("autocomplete", "off");

        $('.field_with_errors').addClass('is-invalid');

        const alerts = $(".alert:not(.permanent)");
        setTimeout(function () {
            alerts.fadeOut();
        }, 8000);

        autosize($('textarea'));

        $("select").each(function () {
            $(this).removeClass("form-select");
            let placeholderText = "Select...";
            if (this.id === 'root-language') {
                placeholderText = 'Select your root language';
            } else if (this.id === 'target-languages') {
                placeholderText = 'Select your target languages';
            }
            console.dir(this.id)
            new SlimSelect({
                select: this,
                settings: {
                    //contentLocation: document.body,
                    contentLocation: this.parentElement,
                    closeOnSelect: !this.hasAttribute("multiple"),
                    openPosition: 'down', // options: auto, up, down
                    placeholderText: placeholderText,
                    maxValuesShown: 200, // defaults to 20, max selected items show in multi-selects
                    hideSelected: true,
                }
            })
        });
    })

app/views/layouts/transeasy/application.js.erb
$("#flash-container").html("<%= j render partial: "transeasy/shared/flash" %>");

<%= yield %>

window.init();

app/views/shared/_nav.html.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-light
  a.navbar-brand href="#"
    | Transeasy
  button.navbar-toggler type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"
    span.navbar-toggler-icon

  div.collapse.navbar-collapse#navbarSupportedContent
    ul.navbar-nav.mr-auto
      li.nav-item.active
        a.nav-link.current href="#" Home
      li.nav-item
        a.nav-link href="#" Link
      li.nav-item.dropdown
        a.nav-link.dropdown-toggle href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
          | Dropdown
        .dropdown-menu aria-labelledby="navbarDropdown"
          a.dropdown-item href="#" Action
          a.dropdown-item href="#" Another action
          .dropdown-divider
          a.dropdown-item href="#" Something else here
      li.nav-item
        a.nav-link.disabled href="#" Disabled

  form.form-inline.my-2.my-lg-0
    div.input-group
      input.form-control.mr-sm-2 type="search" placeholder="Search" aria-label="Search"
      button.btn.btn-outline-success.my-2.my-sm-0 type="submit" Search

javascript:
    document.addEventListener("DOMContentLoaded", function() {
        var dropdownToggleList = [].slice.call(document.querySelectorAll('[data-bs-toggle="dropdown"]'));
        dropdownToggleList.map(function (dropdownToggle) {
            return new bootstrap.Dropdown(dropdownToggle);
        });
    })

app/views/transeasy/shared/_flash.html.slim
#flash-container
  - flash.each do |name, msg|
    - if msg.is_a?(String)
      .alert.alert-dismissible class="alert-#{name.to_s == "notice" ? "success" : "danger"}"
        button.btn-close type="button" data-bs-dismiss="alert"
        span id="flash_#{name}" = msg

  - flash.clear

app/views/transeasy/shared/_nav.html.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-light
  a.navbar-brand href="#"
    | Transeasy
  button.navbar-toggler type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"
    span.navbar-toggler-icon

  div.collapse.navbar-collapse#navbarSupportedContent
    ul.navbar-nav.mr-auto
      li.nav-item.active
        a.nav-link.home.current href="#{root_path}" Home
      li.nav-item.active
        a.nav-link.setup.current href="#{setup_path}" Setup
      / li.nav-item.dropdown
        a.nav-link.dropdown-toggle href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
          | Dropdown
        .dropdown-menu aria-labelledby="navbarDropdown"
          a.dropdown-item href="#" Action
          a.dropdown-item href="#" Another action
          .dropdown-divider
          a.dropdown-item href="#" Something else here
      / li.nav-item
        a.nav-link.disabled href="#" Disabled

  form.form-inline.my-2.my-lg-0
    div.input-group
      input.form-control.mr-sm-2 type="search" placeholder="Search" aria-label="Search"
      button.btn.btn-outline-success.my-2.my-sm-0 type="submit" Search

app/views/transeasy/translations/edit_translation_file.html.slim
- action = @translation_file.persisted? ? 'Update' : 'Create'
h1.page-title Transeasy #{action} Translation File
p
- file_exists = @translation_file.persisted?
= form_with model: @translation_file, url: (file_exists ? update_translation_file_translations_path : create_translation_file_translations_path), method: (file_exists ?  :patch : :post) do |f|
  p
  = f.label('Translation file name (file will automatically be suffixed with language) : ', class: 'mr-5')
  = f.text_field :file_name, required: true, value: f.object&.file_name
  = f.hidden_field :id, value: f.object&.id

  p
  = f.submit("#{action} Translation File", class: 'btn btn-primary mr-5')

  - if @translation_file.persisted?
    = link_to 'Delete Translation File', delete_translation_file_translations_path(id: f.object), class: 'btn btn-danger mr-5', method: :patch, data: { confirm: 'Warning - all translations for this file will be destroyed. Are you sure you want to delete the file'}

  p
  = link_to "Edit Translations", edit_translations_translations_path(id: f.object), class: 'btn btn-primary'

app/views/transeasy/translations/edit_translations.html.slim
h1.page-title Edit Translations
- translations.each do |t|
  - raise

app/views/transeasy/translations/import_translation_file.html.slim
h1.page-title Transeasy Import Translation File
= form_with model: Transeasy::TranslationFile, url: save_setup_translations_path, method: :post do |f|
  = f.file_field 'Select translation file', accept: '.yml'

  p
  = f.submit('Import Translation File', class: 'btn btn-primary')

app/views/transeasy/translations/index.html.slim
h1.page-title Transeasy Home

= form_with model: @translation_files, url: save_setup_translations_path, method: :post do |f|
  - if @translation_files
    - @translation_files.each do |tf|
      p =  link_to "Edit Translation File : #{tf[:file_name]}", edit_translation_file_translations_path(id: tf), class: 'btn btn-info'

  p
  = link_to "Import Translation File", import_translation_file_translations_path, class: 'btn btn-primary'
  p
  = link_to "Create Translation File", edit_translation_file_translations_path, class: 'btn btn-primary'

app/views/transeasy/translations/setup.html.slim
h1.page-title Transeasy Setup
= form_with model: @settings, url: save_setup_translations_path, method: :post do |f|
  .row.align-items-center.mb-5.mt-5
    .col-auto
      = f.label('Primary language:')
    .col-auto
      = select_tag(:root_language, options_for_select(Transeasy.config.all_languages.map{|l| l[:title] }.sort, f.object&.root_language), prompt: 'Select your root language', class: 'form-select', style: 'min-width: 200px', id: 'root-language')

  .row.align-items-center.mb-5
    .col-auto
      = f.label('Target languages:')
    .col-auto
      - target_languages = f.object&.target_languages ? JSON.parse(f.object&.target_languages) : []
      = select_tag(:target_languages, options_for_select(Transeasy.config.all_languages.map{|l| l[:title] }.sort, target_languages), multiple: true, class: 'form-select', style: 'min-width: 200px', id: 'target-languages')

  .row.align-items-center.mb-5.mt-5
    .col-auto
      = f.label('Translation engine:')
    .col-auto
      = select_tag(:translation_engine, options_for_select(Transeasy.config.all_translation_engines.map{|l| l[:name] }.sort, f.object&.translation_engine), prompt: 'Select your translation engine, if you are using one', class: 'form-select', style: 'min-width: 400px', id: 'translation-engine')

  .row.align-items-center.mb-5.mt-5
    .col-auto
      = f.label('Translation engine parameters:')

    .col-auto
      = f.text_field(:translation_engine_parameters, value: f.object&.translation_engine_parameters, style: 'width: 500px')

  .row.align-items-center.mb-5.mt-5
    .col-auto
      = f.submit('Update Settings', class: 'btn btn-primary btn-sm')